# Generated by Django 3.2.4 on 2021-06-25 16:25

from django.db import migrations, models
import rooms.models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_votes_to_skip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='guest_can_skip',
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=rooms.models.generateUniqueCode, max_length=8, unique=True),
        ),
    ]
